application: isb-cgc
version: wires-01
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /.*
  script: ui-wires.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest